version: '2'

services:
  app:
    image: 'shushiki/edufood:latest'
    container_name: app
    ports:
    - '8090:8090'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/edufood
      - SPRING_DATASOURCE_USERNAME=edufood
      - SPRING_DATASOURCE_PASSWORD=Shrjancik238
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
   image: mysql:5.7
   container_name: db
   volumes:
     - postgres-data:/var/lib/mysql
   ports:
     - '33060:3306'
   environment:
     MYSQL_ROOT_PASSWORD: Shrjancik238
     MYSQL_DATABASE: edufood
     MYSQL_USER: edufood
     MYSQL_PASSWORD: Shrjancik238
volumes:
  postgres-data: